version: 2.1

jobs:
  build:
    working_directory: ~/Group6_srccode
    docker:
      - image: "circleci/Group6_srccode"
    steps:
      - checkout
      - run: Group6_srccode\Group6_srccode\src\atm_fingerprint\ && javac ATMmain.java && java ATMmain
  test:
    working_directory: ~/Group6_srccode
    docker:
      - image: "circleci/Group6_srccode"
    steps:
      - checkout
      - run: Group6_srccode\Group6_srccode\src\atm_fingerprint\ && javac ATMmain.java && java ATMmain

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build